### ISSUE TITLE
Something moved the layout of the pagination around

### ISSUE THREAD

**Issue by BigActual** [VLSLgithub/VL-theme-V1#76]
### How can the issue be reproduced?
Go to blog archive and scroll down to see the pagination
### Link to the page in question:
https://vibrantlifeseniorliving.com/blog/
### Screenshot of the problem:
![image](https://user-images.githubusercontent.com/8271108/71131967-35508f00-21c4-11ea-8070-7a944bca808a.png)
### What does your environment look like?
Mac OSx Chrome
- What Operating System are you running? (Windows 10, Mac OS X, Android, iOS, etc.)
- What Web Browser are you using?
- What is your screen resolution? (If you're on a mobile device, you can just list your device here)

### Additional context?

**Comment by d4mation** [comment]
Interesting. Maybe WP changed the DOM for that in an update? I'll take a look tomorrow.
